from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(410, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Displaylabel = QtWidgets.QLabel(self.centralwidget)
        self.Displaylabel.setGeometry(QtCore.QRect(10, 10, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Displaylabel.setFont(font)
        self.Displaylabel.setFrameShape(QtWidgets.QFrame.Box)
        self.Displaylabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Displaylabel.setLineWidth(5)
        self.Displaylabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Displaylabel.setObjectName("Displaylabel")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("CE"))
        self.pushButton.setGeometry(QtCore.QRect(30, 110, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")           #  C
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.delete_it())
        self.pushButton_2.setGeometry(QtCore.QRect(120, 110, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("/"))
        self.pushButton_3.setGeometry(QtCore.QRect(210, 110, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("*"))
        self.pushButton_4.setGeometry(QtCore.QRect(300, 110, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.equal_to())
        self.pushButton_5.setGeometry(QtCore.QRect(320, 10, 81, 81))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("-"))
        self.pushButton_10.setGeometry(QtCore.QRect(300, 200, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("7"))
        self.pushButton_11.setGeometry(QtCore.QRect(210, 200, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("9"))
        self.pushButton_12.setGeometry(QtCore.QRect(30, 200, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("8"))
        self.pushButton_13.setGeometry(QtCore.QRect(120, 200, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("+"))
        self.pushButton_14.setGeometry(QtCore.QRect(300, 290, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("4"))
        self.pushButton_15.setGeometry(QtCore.QRect(210, 290, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("6"))
        self.pushButton_16.setGeometry(QtCore.QRect(30, 290, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("5"))
        self.pushButton_17.setGeometry(QtCore.QRect(120, 290, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("2"))
        self.pushButton_18.setGeometry(QtCore.QRect(120, 380, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("3"))
        self.pushButton_19.setGeometry(QtCore.QRect(30, 380, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("1"))
        self.pushButton_20.setGeometry(QtCore.QRect(210, 380, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("00"))
        self.pushButton_21.setGeometry(QtCore.QRect(300, 380, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("."))
        self.pushButton_22.setGeometry(QtCore.QRect(300, 470, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("sin"))
        self.pushButton_23.setGeometry(QtCore.QRect(30, 470, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("0"))
        self.pushButton_24.setGeometry(QtCore.QRect(210, 470, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("cos"))
        self.pushButton_25.setGeometry(QtCore.QRect(120, 470, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName("pushButton_25")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 410, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def delete_it(self):
        output= self.Displaylabel.text()
        output= output[:-1]
        self.Displaylabel.setText(output)
    def equal_to(self):
        output= str(self.Displaylabel.text())
        ind=output.find("sin")
        # self.Displaylabel.setText(str(ind))

        if ind!=-1: #as if not there then -1 ind
            num=int(output[ind + 3:])
            res= (math.sin(math.radians(num)))
            self.Displaylabel.setText(str(res))
        else:
            res = eval(output)
            self.Displaylabel.setText(str(res))


    def press_it(self,pressed):
        if pressed=="CE":
            self.Displaylabel.setText("0")
        else:
            if self.Displaylabel.text() == "0":
                self.Displaylabel.setText("")
            self.Displaylabel.setText(f"{self.Displaylabel.text()}{pressed}")
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.Displaylabel.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "CE"))
        self.pushButton_2.setText(_translate("MainWindow", "C"))
        self.pushButton_3.setText(_translate("MainWindow", "/"))
        self.pushButton_4.setText(_translate("MainWindow", "x"))
        self.pushButton_5.setText(_translate("MainWindow", "="))
        self.pushButton_10.setText(_translate("MainWindow", "-"))
        self.pushButton_11.setText(_translate("MainWindow", "7"))
        self.pushButton_12.setText(_translate("MainWindow", "9"))
        self.pushButton_13.setText(_translate("MainWindow", "8"))
        self.pushButton_14.setText(_translate("MainWindow", "+"))
        self.pushButton_15.setText(_translate("MainWindow", "4"))
        self.pushButton_16.setText(_translate("MainWindow", "6"))
        self.pushButton_17.setText(_translate("MainWindow", "5"))
        self.pushButton_18.setText(_translate("MainWindow", "2"))
        self.pushButton_19.setText(_translate("MainWindow", "3"))
        self.pushButton_20.setText(_translate("MainWindow", "1"))
        self.pushButton_21.setText(_translate("MainWindow", "00"))
        self.pushButton_22.setText(_translate("MainWindow", "."))
        self.pushButton_23.setText(_translate("MainWindow", "sin"))
        self.pushButton_24.setText(_translate("MainWindow", "0"))
        self.pushButton_25.setText(_translate("MainWindow", "cos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
